import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>TM Pick n Pay Zimbabwe</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className='container'>
       
      </main>
   </>
  );
}
